---
name: Push mirrored docker images
on:
  push:
    branches:
      - master
    paths:
      - server/scripts/mirror-docker-images.*

jobs:
  build-docker:
    name: cd/Push mirrored docker images
    if: github.repository_owner == 'mattermost'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mattermost project
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: cd/Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEV_TOKEN }}
      - name: cd/Run image upload script
        env:
          IMAGES_FILE: server/scripts/mirror-docker-images.json
          DRY_RUN: no
        run: ./server/scripts/mirror-docker-images.sh
